### ISSUE TITLE
makefile y archivos .s

### ISSUE THREAD

**Issue by royconejo** [epernia/firmware_v3#3]
Actualmente makefile busca archivos .s en vez de .S
Pediria el cambio de extension a .S por dos motivos:

1) GNU Assembler distingue entre las dos. A .S le pasa el preprocesador de C y a .s no. Tuvimos algunos problemas en la cursada de Arq de Micros ya que se queria usar #define para definir nombres amigables a los registros y no se podia.

2) Hay codigo .S dentro del proyecto (ejemplos de LPCOpen).

**Comment by epernia** [comment]
Ver:
https://github.com/epernia/cese-edu-ciaa-template/pull/4

**Comment by epernia** [comment]
Solucionado
