### ISSUE TITLE
Same board.h for ciaa_nxp and edu_ciaa_nxp?

### ISSUE THREAD

**Issue by luw-aistech** [epernia/firmware_v3#48]
\libs\lpc_open\boards

**Comment by gustavojm** [comment]
Hi Eric, I have the same question as luw-aistech. I find different GPIO assignments on each board. This is what I've found for CIAA-NXP

		{ 3, 0 }, 	// GPIO0	PIN74	P6_1	FUNCTION0	GPIO3[0]
		{ 5, 5 }, 	// GPIO1	PIN91	P2_5	FUNCTION4	GPIO5[5]
		{ 3, 8 }, 	// GPIO2	PIN102	P7_0	FUNCTION0	GPIO3[8]
		{ 5, 15 },	// GPIO3	PIN85	P6_7	FUNCTION4	GPIO5[15]
				// GPIO4	I2S0_RX_MCLK
				// GPIO5	I2S0_RX_SCK
				// GPIO6	I2S0_TX_SCK
		{ 3, 2 }, 	// GPIO7	PIN79	P6_3	FUNCTION0	GPIO3[2]
		{ 0, 5 } 	// GPIO8	PIN83	P6_6	FUNCTION0	GPIO0[5]
				// GPIO9	AUX_CLK
				// GPIO10	RTC_ALARM
				// GPIO11	WAKEUP0
				// GPIO12	RESET

Best regards,-
